### ISSUE TITLE
frame fork

### ISSUE THREAD

**Issue by callerc1** [Silom/ngFrame#11]
Hi Silom,

I had a question about the frame fork and specifically the `server/web/index.js` file. I understand that the `/assets/` route serves the front end files however i'm unsure at what the `/views/` route actually does or is trying to do? Can you enlighten me?

Thanks

**Comment by callerc1** [comment]
Im thinking its for static files for modules but i cant see any being used? in fact everything is compiled to `bundle.js` in `/dist`.

**Comment by Silom** [comment]
Hey Callerc,
you are right, since I switched to Jadeify there is no need for the view/template request to frame. All template's get loaded initially and only the dynamic data from the api needs to be requested.

Im sorry, I was busy with a huge project the last two month, but I will write this down to my refactoring steps and start developing on ngFrame asap.

Thanks for the feedback.

**Comment by callerc1** [comment]
Awesome, as i thought. Thanks for clarifying.

**Comment by Silom** [comment]
I updated it.
